### ISSUE TITLE
RS-GOPRO synthetic dataset

### ISSUE THREAD

**Issue by kaiq663** [shangwei5/SelfDRSC#1]
Hi, Links you provided have been a failure, : ( 

and I try to download the RS-GOPRO dataset from IFED, but the file is about 50G on google drive, which is prone to disconnect.

Would you please be kind to reupload the dataset in BaiduDisk?Thanks

**Comment by shangwei5** [comment]
Thank you for your reminder. We have uploaded the dataset to Baidu Netdisk and updated the README.
[Baidu Netdisk](https://pan.baidu.com/s/1LNjrFYJJAUgt3H4ZUumOJw?pwd=vsad) (password: vsad).
